server:
  port: 8092   
  #server:
  #port: 9001
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-user
  registry:
    address: zookeeper://192.168.88.132:2181?backup=192.168.88.132:2182,192.168.88.132:2183 
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp



  